#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# TRV Controller - Constants © Autolog 2018
#

# plugin Constants

try:
    # noinspection PyUnresolvedReferences
    import indigo
except ImportError, e:
    pass

TRV_DEVICE_TYPEID = 'trvType'  # See definition in Devices.xml

# Types of Devices

TRV = 0
VALVE = 1
REMOTE = 2

# Types of Devices (Translation)

DEVICE_TYPE_TRANSLATION = dict()
DEVICE_TYPE_TRANSLATION[TRV] = 'TRV'
DEVICE_TYPE_TRANSLATION[VALVE] = 'VALVE'
DEVICE_TYPE_TRANSLATION[REMOTE] = 'REMOTE'

# Race Condition Limit used in plugin.py (Method deviceUpdated)
RACE_CONDITION_LIMIT = 40

# HVAC Modes

HVAC_OFF = indigo.kHvacMode.Off  # = 0
HVAC_HEAT = indigo.kHvacMode.Heat  # = 1
HVAC_COOL = indigo.kHvacMode.Cool  # = 2
HVAC_AUTO = indigo.kHvacMode.HeatCool  # = 3
HVAC_ENERGY_HEAT = 11
HVAC_FULL_POWER = 15
HVAC_VALVE_CONTROL = 31
RESET_TO_HVAC_HEAT = 99 

# HVAC Modes (Translation)

HVAC_TRANSLATION = dict()
HVAC_TRANSLATION[HVAC_OFF] = 'Off'
HVAC_TRANSLATION[HVAC_HEAT] = 'Heat'
HVAC_TRANSLATION[HVAC_COOL] = 'Cool [Disallowed!]'
HVAC_TRANSLATION[HVAC_AUTO] = 'Auto'
HVAC_TRANSLATION[HVAC_ENERGY_HEAT] = 'Energy Heat [Spirit]'
HVAC_TRANSLATION[HVAC_FULL_POWER] = 'Full Power [Spirit]'
HVAC_TRANSLATION[HVAC_VALVE_CONTROL] = 'Valve Control [Spirit]'
HVAC_TRANSLATION[RESET_TO_HVAC_HEAT] = 'Reset To Heat'

# TRV Controller Control Modes

CONTROLLER_MODE_INITIALISATION = 0
CONTROLLER_MODE_AUTO = 1
CONTROLLER_MODE_UI = 2
CONTROLLER_MODE_TRV_HARDWARE = 3
CONTROLLER_MODE_TRV_UI = 4
CONTROLLER_MODE_REMOTE_HARDWARE = 5
CONTROLLER_MODE_REMOTE_UI = 6

# TRV Controller Control Modes (Translation)

CONTROLLER_MODE_TRANSLATION = dict()
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_INITIALISATION] = 'Initialisation'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_AUTO] = 'Auto Schedule Control'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_UI] = 'UI Control'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_TRV_HARDWARE] = 'TRV Hardware Control'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_TRV_UI] = 'TRV UI Control'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_REMOTE_HARDWARE] = 'Remote Hardware Control'
CONTROLLER_MODE_TRANSLATION[CONTROLLER_MODE_REMOTE_UI] = 'Remote UI Control'

# Update Keys

UPDATE_CONTROLLER_MODE = 0
UPDATE_CONTROLLER_HVAC_OPERATION_MODE = 1
UPDATE_CONTROLLER_TEMPERATURE = 2
UPDATE_CONTROLLER_HEAT_SETPOINT = 3
UPDATE_CONTROLLER_VALVE_PERCENTAGE = 4

UPDATE_TRV_BATTERY_LEVEL = 5
UPDATE_TRV_HVAC_OPERATION_MODE = 6
UPDATE_TRV_TEMPERATURE = 7
UPDATE_TRV_HEAT_SETPOINT = 8
UPDATE_TRV_HEAT_SETPOINT_FROM_DEVICE = 9

UPDATE_REMOTE_BATTERY_LEVEL = 10
UPDATE_REMOTE_TEMPERATURE = 11
UPDATE_REMOTE_HEAT_SETPOINT = 12
UPDATE_REMOTE_HEAT_SETPOINT_FROM_DEVICE = 13

UPDATE_ZWAVE_WAKEUP_INTERVAL = 14
UPDATE_ZWAVE_HVAC_OPERATION_MODE_ID = 15
UPDATE_ZWAVE_EVENT_RECEIVED_TRV = 16
UPDATE_ZWAVE_EVENT_RECEIVED_REMOTE = 17
UPDATE_ZWAVE_EVENT_SENT_TRV = 18
UPDATE_ZWAVE_EVENT_SENT_REMOTE = 19

UPDATE_EVENT_RECEIVED_REMOTE = 20

# Update Keys (Translation)

UPDATE_TRANSLATION = dict()

UPDATE_TRANSLATION[UPDATE_CONTROLLER_MODE] = 'UPDATE CONTROLLER MODE'
UPDATE_TRANSLATION[UPDATE_CONTROLLER_HVAC_OPERATION_MODE] = 'UPDATE CONTROLLER HVAC OPERATION MODE'
UPDATE_TRANSLATION[UPDATE_CONTROLLER_TEMPERATURE] = 'UPDATE CONTROLLER TEMPERATURE'
UPDATE_TRANSLATION[UPDATE_CONTROLLER_HEAT_SETPOINT] = 'UPDATE CONTROLLER HEAT SETPOINT'
UPDATE_TRANSLATION[UPDATE_CONTROLLER_VALVE_PERCENTAGE] = 'UPDATE CONTROLLER VALVE PERCENTAGE'

UPDATE_TRANSLATION[UPDATE_TRV_BATTERY_LEVEL] = 'UPDATE TRV BATTERY LEVEL'
UPDATE_TRANSLATION[UPDATE_TRV_HVAC_OPERATION_MODE] = 'UPDATE TRV HVAC OPERATION MODE'
UPDATE_TRANSLATION[UPDATE_TRV_TEMPERATURE] = 'UPDATE TRV TEMPERATURE'
UPDATE_TRANSLATION[UPDATE_TRV_HEAT_SETPOINT] = 'UPDATE TRV HEAT SETPOINT'
UPDATE_TRANSLATION[UPDATE_TRV_HEAT_SETPOINT_FROM_DEVICE] = 'UPDATE TRV HEAT SETPOINT FROM DEVICE'

UPDATE_TRANSLATION[UPDATE_REMOTE_BATTERY_LEVEL] = 'UPDATE REMOTE BATTERY LEVEL'
UPDATE_TRANSLATION[UPDATE_REMOTE_TEMPERATURE] = 'UPDATE REMOTE TEMPERATURE'
UPDATE_TRANSLATION[UPDATE_REMOTE_HEAT_SETPOINT] = 'UPDATE REMOTE HEAT SETPOINT'
UPDATE_TRANSLATION[UPDATE_REMOTE_HEAT_SETPOINT_FROM_DEVICE] = 'UPDATE REMOTE HEAT SETPOINT FROM DEVICE'

UPDATE_TRANSLATION[UPDATE_ZWAVE_WAKEUP_INTERVAL] = 'UPDATE ZWAVE WAKEUP INTERVAL'
UPDATE_TRANSLATION[UPDATE_ZWAVE_HVAC_OPERATION_MODE_ID] = 'UPDATE ZWAVE HVAC OPERATION MODE ID'

UPDATE_TRANSLATION[UPDATE_ZWAVE_EVENT_RECEIVED_TRV] = 'UPDATE ZWAVE EVENT RECEIVED TRV'
UPDATE_TRANSLATION[UPDATE_ZWAVE_EVENT_RECEIVED_REMOTE] = 'UPDATE ZWAVE EVENT RECEIVED REMOTE'

UPDATE_TRANSLATION[UPDATE_ZWAVE_EVENT_SENT_TRV] = 'UPDATE ZWAVE EVENT SENT TRV'
UPDATE_TRANSLATION[UPDATE_ZWAVE_EVENT_SENT_REMOTE] = 'UPDATE ZWAVE EVENT SENT REMOTE'

UPDATE_TRANSLATION[UPDATE_EVENT_RECEIVED_REMOTE] = 'UPDATE EVENT RECEIVED REMOTE'

# Z-Wave Command Classes

ZWAVE_COMMAND_CLASS_SWITCH_MULTILEVEL = '26'  # hex
ZWAVE_COMMAND_CLASS_SENSOR_MULTILEVEL = '31'  # hex
ZWAVE_COMMAND_CLASS_THERMOSTAT_MODE_CONTROL = '40'  # hex
ZWAVE_COMMAND_CLASS_THERMOSTAT_SETPOINT = '43'  # hex
ZWAVE_COMMAND_CLASS_THERMOSTAT_CLIMATE_CONTROL_SCHEDULE = '46'  # hex
ZWAVE_COMMAND_CLASS_BATTERY = '80'  # hex
ZWAVE_COMMAND_CLASS_WAKEUP = '84'  # hex

# Z-Wave Command Classes (translation)

ZWAVE_COMMAND_CLASS_TRANSLATION = dict()
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_SWITCH_MULTILEVEL] = 'Switch Multilevel'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_SENSOR_MULTILEVEL] = 'Sensor Multilevel'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_THERMOSTAT_MODE_CONTROL] = 'Thermostat Mode Control'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_THERMOSTAT_SETPOINT] = 'Thermostat Setpoint'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_THERMOSTAT_CLIMATE_CONTROL_SCHEDULE] = 'Thermostat Climate Control Schedule'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_BATTERY] = 'Battery'
ZWAVE_COMMAND_CLASS_TRANSLATION[ZWAVE_COMMAND_CLASS_WAKEUP] = 'Wakeup'


# Z-Wave Command Verbs

ZWAVE_COMMAND_VERB_01 = '01'
ZWAVE_COMMAND_VERB_02 = '02'
ZWAVE_COMMAND_VERB_03 = '03'
ZWAVE_COMMAND_VERB_04 = '04'
ZWAVE_COMMAND_VERB_05 = '05'
ZWAVE_COMMAND_VERB_06 = '06'
ZWAVE_COMMAND_VERB_07 = '07'
ZWAVE_COMMAND_VERB_08 = '08'
ZWAVE_COMMAND_VERB_09 = '09'


# Z-Wave Command Verbs (translation) 

ZWAVE_COMMAND_VERB_TRANSLATION = dict()
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_01] = 'Set'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_02] = 'Get'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_03] = 'Report'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_04] = 'Verb 04'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_05] = 'Verb 05'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_06] = 'Verb 06'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_07] = 'Verb 07'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_08] = 'Verb 08'
ZWAVE_COMMAND_VERB_TRANSLATION[ZWAVE_COMMAND_VERB_09] = 'Verb 09'


# Z-Wave Command Sublasses (translation)

ZWAVE_COMMAND_SUBCLASS_STATUS = '02'  # hex
ZWAVE_COMMAND_SUBCLASS_SET = '01'  # hex

# Z-Wave Command Sublasses (translation)

ZWAVE_COMMAND_SUBCLASS_TRANSLATION = dict()
ZWAVE_COMMAND_SUBCLASS_TRANSLATION[ZWAVE_COMMAND_SUBCLASS_STATUS] = 'Get Valve Status'
ZWAVE_COMMAND_SUBCLASS_TRANSLATION[ZWAVE_COMMAND_SUBCLASS_SET] = 'Set Valve Opening to'  # May need to cahnge this if it needs to be more general!

# Heat Source Type

HEAT_SOURCE_NOT_FOUND = 0
HEAT_SOURCE_CONTROL_HVAC = 1
HEAT_SOURCE_CONTROL_RELAY = 2

# HEAT SOURCE STATE
HEAT_SOURCE_OFF = 0
HEAT_SOURCE_ON = 1
HEAT_SOURCE_INITIALISE = 9

# Schedule List Entry

SCHEDULE_TIME_UI = 0
SCHEDULE_SETPOINT = 1
SCHEDULE_ID = 2
SCHEDULE_ACTIVE = 3

# Boost mode
BOOST_MODE_SELECT = 0
BOOST_MODE_DELTA_T = 1
BOOST_MODE_SETPOINT = 2
BOOST_MODE_INACTIVE = 3
BOOST_MODE_NOT_SET = 9

# Boost mode [translation]
BOOST_MODE_TRANSLATION = dict()
BOOST_MODE_TRANSLATION[BOOST_MODE_SELECT] = 'Select Boost mode'
BOOST_MODE_TRANSLATION[BOOST_MODE_DELTA_T] = 'Delta T Boost'
BOOST_MODE_TRANSLATION[BOOST_MODE_SETPOINT] = 'Setpoint Boost'
BOOST_MODE_TRANSLATION[BOOST_MODE_INACTIVE] = ''


# Device Start HEAT Setpoint Method
DEVICE_START_SETPOINT  = dict()
DEVICE_START_SETPOINT_DEVICE_MINIMUM = 1
DEVICE_START_SETPOINT_LEAVE_AS_IS = 2
DEVICE_START_SETPOINT_SPECIFIED = 3

# Device Start HEAT Setpoint Method [translation]
DEVICE_START_SETPOINT_TRANSLATION  = dict()
DEVICE_START_SETPOINT_TRANSLATION[DEVICE_START_SETPOINT_DEVICE_MINIMUM] = 'Device minimum'
DEVICE_START_SETPOINT_TRANSLATION[DEVICE_START_SETPOINT_LEAVE_AS_IS] = 'Leave as is'
DEVICE_START_SETPOINT_TRANSLATION[DEVICE_START_SETPOINT_SPECIFIED] = 'Specified'

# TRV Model Properties List Entry indexes in dictionary self.globals['supportedTrvModels'] which is keyed on TRV model name

TRV_MODEL_SUPPORTS_WAKEUP = 0
TRV_MODEL_SUPPORTS_TEMPERATURE_REPORTING = 1
TRV_MODEL_SUPPORTS_HVAC_ON_OFF = 2
TRV_MODEL_SUPPORTS_VALVE_CONTROL = 3
TRV_MODEL_SUPPORTS_MANUAL_SETPOINT = 4
TRV_MODEL_SETPOINT_HEAT_MINIMUM = 5
TRV_MODEL_SETPOINT_HEAT_MAXIMUM = 6



# Plugin Internal commands
CMD_STOP_THREAD = 0
CMD_UPDATE_TRV_CONTROLLER_STATES = 1
CMD_UPDATE_TRV_STATES = 2
CMD_UPDATE_VALVE_STATES = 3
CMD_UPDATE_REMOTE_STATES = 4
CMD_CONTROL_HEATING_SOURCE = 5
CMD_KEEP_HEAT_SOURCE_CONTROLLER_ALIVE = 6
CMD_CONTROL_TRV = 7
CMD_PROCESS_HEATING_SCHEDULE = 8
CMD_DELAY_COMMAND = 9
CMD_RESTATE_SCHEDULES = 10
CMD_BOOST = 11
CMD_BOOST_CANCEL = 12
CMD_ADVANCE = 13
CMD_ADVANCE_CANCEL = 14
CMD_EXTEND = 15
CMD_EXTEND_CANCEL = 16
CMD_UPDATE_CSV_FILE = 17
CMD_UPDATE_ALL_CSV_FILES = 18
CMD_UPDATE_ALL_CSV_FILES_VIA_POSTGRESQL = 19
CMD_RESET_SCHEDULE_TO_DEVICE_DEFAULTS = 20 

# Plugin Internal commands (translation)
CMD_TRANSLATION = dict()
CMD_TRANSLATION[CMD_STOP_THREAD] = 'STOP THREAD'
CMD_TRANSLATION[CMD_UPDATE_TRV_CONTROLLER_STATES] = 'UPDATE TRV CONTROLLER STATES'
CMD_TRANSLATION[CMD_UPDATE_TRV_STATES] = 'UPDATE TRV STATES'
CMD_TRANSLATION[CMD_UPDATE_VALVE_STATES] = 'UPDATE VALVE STATES'
CMD_TRANSLATION[CMD_UPDATE_REMOTE_STATES] = 'UPDATE REMOTE STATES'
CMD_TRANSLATION[CMD_CONTROL_HEATING_SOURCE] = 'CONTROL HEATING SOURCE'
CMD_TRANSLATION[CMD_KEEP_HEAT_SOURCE_CONTROLLER_ALIVE] = 'KEEP HEAT SOURCE CONTROLLER ALIVE'
CMD_TRANSLATION[CMD_CONTROL_TRV] = 'CONTROL TRV'
CMD_TRANSLATION[CMD_PROCESS_HEATING_SCHEDULE] = 'INITIALISE HEATING SCHEDULE'
CMD_TRANSLATION[CMD_DELAY_COMMAND] = 'DELAY COMMAND'
CMD_TRANSLATION[CMD_RESTATE_SCHEDULES] = 'RESTATE SCHEDULES'
CMD_TRANSLATION[CMD_BOOST] = 'BOOST'
CMD_TRANSLATION[CMD_BOOST_CANCEL] = 'BOOST CANCEL'
CMD_TRANSLATION[CMD_ADVANCE] = 'ADVANCE'
CMD_TRANSLATION[CMD_ADVANCE_CANCEL] = 'ADVANCE CANCEL'
CMD_TRANSLATION[CMD_EXTEND] = 'EXTEND'
CMD_TRANSLATION[CMD_EXTEND_CANCEL] = 'EXTEND CANCEL'
CMD_TRANSLATION[CMD_UPDATE_CSV_FILE] = 'UPDATE CSV FILE'
CMD_TRANSLATION[CMD_UPDATE_ALL_CSV_FILES] = 'UPDATE ALL CSV FILES'
CMD_TRANSLATION[CMD_UPDATE_ALL_CSV_FILES_VIA_POSTGRESQL] = 'UPDATE ALL CSV FILES VIA POSTGRESQL'
CMD_TRANSLATION[CMD_RESET_SCHEDULE_TO_DEVICE_DEFAULTS] = 'RESET SCHEDULE TO DEVICE DEFAULTS'

# Advance Command Types

ADVANCE_NEXT = 0
ADVANCE_NEXT_ON = 1
ADVANCE_NEXT_OFF = 2

# Advance Command Types

ADVANCE_TRANSLATION = dict()
ADVANCE_TRANSLATION[ADVANCE_NEXT] = 'ADVANCE'
ADVANCE_TRANSLATION[ADVANCE_NEXT_ON] = 'ADVANCE ON'
ADVANCE_TRANSLATION[ADVANCE_NEXT_OFF] = 'ADVANCE OFF'

# QUEUE Priorities
QUEUE_PRIORITY_STOP_THREAD    = 0
QUEUE_PRIORITY_INIT_DISCOVERY = 50
QUEUE_PRIORITY_WAVEFORM       = 100
QUEUE_PRIORITY_COMMAND_HIGH   = 200
QUEUE_PRIORITY_COMMAND_MEDIUM = 300
QUEUE_PRIORITY_STATUS_HIGH    = 400
QUEUE_PRIORITY_STATUS_MEDIUM  = 500
QUEUE_PRIORITY_DISCOVERY      = 600
QUEUE_PRIORITY_POLLING        = 700
QUEUE_PRIORITY_LOW            = 800
